/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.infomila.autoescola.GUI;

import info.infomila.autoescola.models.Alumne;
import info.infomila.autoescola.models.GestorBDException;
import info.infomila.autoescola.models.Professor;
import info.infomila.autoescola.persistencia.GestorBD;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class GestioAlumne extends javax.swing.JDialog
{
    private Alumne alumne;
    private List<Professor> llProfessors;
    private GestorBD bd;
    
    /**
     * Creates new form GestioAlumne
     */
    public GestioAlumne(java.awt.Frame parent, Alumne alumne, List<Professor> llProfessors, GestorBD bd)
    {
        super(parent,true);
        
        initComponents();
        
        if(alumne != null && llProfessors != null && bd != null)
        {
            this.alumne = alumne;
            this.llProfessors = llProfessors;
            this.bd = bd;
            
            label_titol.setText("Modificació de l'Alumne: " + alumne.getNom() + ", " + alumne.getCognoms());
            
            input_nif.setText(this.alumne.getNif());
            input_nom.setText(this.alumne.getNom());
            input_cognoms.setText(this.alumne.getCognoms());
            input_telefon.setText(this.alumne.getTelefon());
            input_correu.setText(this.alumne.getCorreu());
            input_poblacio.setText(this.alumne.getPoblacio());
            input_adreca.setText(this.alumne.getAdreca());
            
            int i = 0;
            int pos = 0;
            for (Professor professor : llProfessors)
            {
                input_professor.addItem(professor.toString());
                if(professor.getNif().equals(alumne.getProfessor()))
                {
                    pos = i;
                }
                i++;
            }
            input_professor.setSelectedIndex(pos);
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnCrear = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        label_professor = new javax.swing.JLabel();
        input_nif = new javax.swing.JTextField();
        label_nif = new javax.swing.JLabel();
        input_nom = new javax.swing.JTextField();
        label_nom = new javax.swing.JLabel();
        input_cognoms = new javax.swing.JTextField();
        label_cognoms = new javax.swing.JLabel();
        input_correu = new javax.swing.JTextField();
        label_correu = new javax.swing.JLabel();
        input_poblacio = new javax.swing.JTextField();
        label_poblacio = new javax.swing.JLabel();
        input_adreca = new javax.swing.JTextField();
        label_adreca = new javax.swing.JLabel();
        input_telefon = new javax.swing.JTextField();
        label_telefon = new javax.swing.JLabel();
        input_professor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        label_titol = new javax.swing.JLabel();

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCrearActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_professor.setText("Professor");

        label_nif.setText("NIF");

        label_nom.setText("Nom");

        label_cognoms.setText("Cognoms");

        label_correu.setText("Correu");

        label_poblacio.setText("Població");

        label_adreca.setText("Adreça");

        label_telefon.setText("Telèfon de contacte");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        label_titol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nif)
                                    .addComponent(input_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_correu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nom)
                                    .addComponent(input_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(input_correu, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_telefon)
                            .addComponent(input_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_cognoms)
                            .addComponent(input_cognoms, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(input_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_poblacio)
                                        .addComponent(label_professor))
                                    .addGap(129, 129, 129))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(input_poblacio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_adreca)
                                .addComponent(input_adreca, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(label_titol, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_titol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(label_nif)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(label_cognoms)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_cognoms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input_correu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_telefon)
                            .addComponent(label_correu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_adreca)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_poblacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_poblacio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_adreca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(label_professor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCrearActionPerformed
    {//GEN-HEADEREND:event_btnCrearActionPerformed

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
    {//GEN-HEADEREND:event_btnGuardarActionPerformed
        String nif = input_nif.getText();
        String nom = input_nom.getText();
        String cognoms = input_cognoms.getText();
        String telefon = input_telefon.getText();
        String correu = input_correu.getText();
        String poblacio = input_poblacio.getText();
        String adreca = input_adreca.getText();
        Professor professor = llProfessors.get(input_professor.getSelectedIndex());
        
        try
        {
            bd.updateAlumne(new Alumne(nif, nom, cognoms, correu, poblacio, adreca, telefon, professor.getNif(), professor.getNom() + ", " + professor.getCognoms(), 0));
            
            dispose();
        }
        catch (GestorBDException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField input_adreca;
    private javax.swing.JTextField input_cognoms;
    private javax.swing.JTextField input_correu;
    private javax.swing.JTextField input_nif;
    private javax.swing.JTextField input_nom;
    private javax.swing.JTextField input_poblacio;
    private javax.swing.JComboBox<String> input_professor;
    private javax.swing.JTextField input_telefon;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel label_adreca;
    private javax.swing.JLabel label_cognoms;
    private javax.swing.JLabel label_correu;
    private javax.swing.JLabel label_nif;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_poblacio;
    private javax.swing.JLabel label_professor;
    private javax.swing.JLabel label_telefon;
    private javax.swing.JLabel label_titol;
    // End of variables declaration//GEN-END:variables
}
