/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.infomila.autoescola.GUI;

import info.infomila.autoescola.interficie.persistencia.IGestorBD;
import info.infomila.autoescola.models.Alumne;
import info.infomila.autoescola.models.GestorBDException;
import info.infomila.autoescola.models.Practica;
import info.infomila.autoescola.models.Professor;
import info.infomila.autoescola.persistencia.GestorBD;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class GestioPractica extends javax.swing.JDialog
{
    private IGestorBD bd;
    private Practica practica;
    private Alumne alumne;
    
    /**
     * Creates new form GestioAlumne
     */
    public GestioPractica(java.awt.Dialog parent, Practica practica, Alumne alumne, IGestorBD bd)
    {
        super(parent,true);
        
        initComponents();
        
        if(practica != null && bd != null)
        {
            this.practica = practica;
            this.alumne = alumne;
            
            label_titol.setText("Modificació de la pràctica: " + practica.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnCrear = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        label_titol = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        label_observacions = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        input_observacions = new javax.swing.JTextArea();

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCrearActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_titol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        label_observacions.setText("Observacions");

        input_observacions.setColumns(20);
        input_observacions.setRows(5);
        jScrollPane2.setViewportView(input_observacions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_observacions)
                        .addGap(232, 232, 232))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_titol, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_titol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(label_observacions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCrearActionPerformed
    {//GEN-HEADEREND:event_btnCrearActionPerformed

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
    {//GEN-HEADEREND:event_btnGuardarActionPerformed
        try
        {
            String observacions = input_observacions.getText();
            practica.setObservacions(observacions);
            
            try
            {
                bd.updatePractica(practica);
                
                dispose();
            }
            catch (GestorBDException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        catch (GestorBDException ex)
        {
            Logger.getLogger(GestioPractica.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextArea input_observacions;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_observacions;
    private javax.swing.JLabel label_titol;
    // End of variables declaration//GEN-END:variables
}
